output$you_rank_g <- renderPrint({input$you_rank_g})
output$previous_ranking <- renderPrint({input$previous_ranking})
output$genre <- renderPrint({input$genre})
output$season <- renderPrint({input$season})
output$sex <- renderPrint({input$sex})
output$song_type <- renderPrint({input$song_type})
output$active_type <- renderPrint({input$active_type})

output$runtime <- renderPrint({input$runtime})
output$top_freq <- renderPrint({input$top_freq})
output$gg_score <- renderPrint({input$gg_score})
output$nv_score <- renderPrint({input$nv_socre})
output$pd_score <- renderPrint({input$pd_score})
 
output$total_view <- renderPrint({input$total_view})
output$dc_total_numb <- renderPrint({input$dc_total_numb})
output$dC_mean_reccomend <- renderPrint({input$dC_mean_reccomend})
output$dc_mean_views <- renderPrint({input$dc_mean_views})
output$drama_view <- renderPrint({input$drama_view})