---
title: "0426_meeting"
author: "Wonhee Baek"
date: '2020 4 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##brain storming
디시갤러리도 유의한 영햐을 미침 : 긍정적 or 부정적 기사
각 가수별 글이 얼마나 올라와 있는지? 페이지 수로 나ᄂ어 져있으니, 옆에 날짜만 처리해서 처음에서 끝까지 갯수만 세면 되니.. 텍스트 마이닝ᄋ  컴퓨터 용량이 감당이 안될수 있으니. 서버하나 만들어서 돌리면 될듯 함. 멀티 프ᄅ세싱? 병렬처리해서 시간을 단축할 수 있음. 리젠수(주별로 게시글 몇개 올라오느냐)

y값과 x 값? multi class classification 
주별로 x와 y가 따로 따로 나옴; 트레이닝 시키면 됨. 기간별 추이가 있 함/ 전주대비 몇프로 상승/ 순위 예측하기 힘들면, 전주대비 몇프로? 가온차트 1등이 나올 확률이 높은 순서대로 하면 순서가 나오지 않나? 1위 될 확률로 하면 .. 확률값으ᄅ  것은 어떨까? y값이 0,1로 나와야 ...soft 웩스? multi class 하면 될듯. AUR ROC가 나쁜점이 binary 밖에 안됨. 그 F1 score 가 좋음. 

1. multiclass로 해보기
2. 1부터 100위까지 확률값으로 

x 변수 : ost가 맞으면 1, 않으면 0 //지ᄂ  show me the money or 트로트는 구분이 안됨. //앨범명을 쓰면 구분을 해줄 수 있을거 같은데.. 가ᄋ 차트에서 가수 이름 길면 앨범명을 삭제했음. 
DB 하나 만드는 것이 편할듯. 
// 시험ᄒ  있는 6개월에서 1년 정도..
데이터를 정제 하여 모델 돌려보기 6주의 마지막 주차 순위를 ᄋ. 유투브 차트는 18년 4월부터 존재함. 
//가사는 어려울듯하니 제외 하기로(컴퓨터 용량, 시ᄀ  문제)
//가온차트의 모든 내용 (앨범제외) 코드 짜 놨음. 멜론의 좋아요 크롤링, 
//음반ᄉ 추이 예측, 급격하게 올라갔는지 올라가지 않았는지 클러스터링? 예측 y값으로 써야 ᄒ듯. 
//음악 트렌드 예측, 앞으로 몇주간 유행하게 될 장르
//구글트렌드, 뉴스 수가 교호 ᄌ 있을테니 하나만 뽑으면 될듯. 뉴스가 많으면 트렌드가 올라갈테니. 
//페이스북, 인스 팔로워 시간대 별로 차이가 날 수 있음. 
//곡별 좋아요. 누적도 의미가 있음. 
//방송횟ᄉ,라디오 횟수는 어디서 볼 수 있을까? 라디오 홈페이지에 선곡표가 있음. 각 방송3사 별 들어가서 확인해야 할듯. 프로그램마다 선곡표가 다른듯.청취율 높은것 몇개 정ᄒ서 선곡표 만들면 괜찮을듯. 방송 3사 탑3, TBS 교통방송이 높음..
//음악적인 느낌:장르,run time,작곡가/작사가가 반영할 수 있을듯 함. 계절별로 인기 있는 장르: 가중ᄎ  할수 있을듯. 머신 러닝을 돌리면 
//예측렬을 높이려면 PCA 돌리면됨. v1,v2,v3로 되어서 ᄋ 데이터가 합쳐지는지 모름; 1~10..등으로 카테고리화 하면 예측력을 높일 수 있을듯. 
//뮤ᄌ 이미지로 되어 있음. 
//바이브 스트리밍 지수? 가온차트가 여러 서비스를 종합한 것이므로,   찾아서 유의미한것 찾아봐도 됨. 
//19년도 6월부터 12월: 엑셀로 뽑고, 모델을 뭐로 할지 ᄀ(landom forest or 선형회귀 or 베이지안): prototype먼저 만들것. 
//DC는 청파 
//EDA는 r이 편함/ 시각화: 왜곡된 것은 로그변환, scale을 0부터 1까지 정규화 하면 됨. 
