---
title: "파생변수 생성"
author: "2015122026오태환"
date: '2020 5 26 '
output: 
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
fontsize: 10pt
geometry: margin=1in
mainfont: NanumGothic
classoption: a4paper
---

# 1) Import Data
```{r}
library(tidyverse)

data = read_csv("new_merge_data.csv")
summary(data)
```

# 2) 파생변수 만들기

## 2-1) 이전 곡 순위
```{r}
previous_song = data %>% select(artist, name) %>%
  unique() %>% group_by(artist) %>% mutate(previous_song = lag(name,1)) %>% ungroup()
```
### 가수별로 그룹핑을 하고 곡 칼럼을 한 칸씩 밀어 이전 곡 칼럼을 생성했다.

```{r}
data = previous_song %>% merge(data, by = c("name", "artist"))


data = data %>% select(artist, name, previous_song, rank) %>% 
  group_by(name) %>% 
  mutate(top_rank = min(rank)) %>% 
  ungroup() %>% 
  select(-rank) %>% 
  unique() %>% 
  group_by(artist) %>% 
  mutate(previous_song_rank = lag(top_rank, 1)) %>% 
  ungroup() %>% 
  merge(data, by = c("artist", "name", "previous_song")) %>% 
  select(-c("top_rank", "previous_song"))
```
## 이전 곡의 최고 랭킹 칼럼을 만들었다.

## 2-2) 계절 변수 추가

```{r}

data$month = data$month %>% unlist() %>% as.integer()


season = function(x){
  if(any(x == c("3", "4", "5"))){
    return("spring")
  }
  if(any(x == c("6", "7", "8"))){
    return("summer")
  }
  if(any(x == c("9", "10", "11"))){
    return("fall")
  }
  else{
    return("winter")
  }
}


for(i in 1:nrow(data)){
  data$season[i] = season(data$month[i])
}

write.csv(data, "firstmodeldata.csv")
```

### 3,4,5월은 봄, 6,7,8월은 여름, 9,10,11월은 가을, 12,1,2월은 겨울로 하는 칼럼을 만들었다.